### ISSUE TITLE
Find.t fails with Strawberry Perl 5.14.4

### ISSUE THREAD

**Issue by GwenDragon** [schwern/URI-Find#9]
URI::Find can not be tested with Strawberry Perl 5.14.4.1 (32bit). 
As a result the install with cpan fails.

Latest Test::More (shown as EXODIST/Test-Simple-1.001003.tar.gz with cpan) is installed.

cpan URI::FInd shows:

	PERL-5.14 T:\>cpan URI::Find
	CPAN: CPAN::SQLite loaded ok (v0.203)
	Database was generated on Mon, 14 Jul 2014 08:29:51 GMT

	Running install for module 'URI::Find'
	CPAN: Digest::SHA loaded ok (v5.92)
	CPAN: Compress::Zlib loaded ok (v2.064)
	Checksum for C:\strawberry\cpan\sources\authors\id\M\MS\MSCHWERN\URI-Find-20140709.tar.gz ok
	CPAN: Archive::Tar loaded ok (v2.00)
	CPAN: File::Temp loaded ok (v0.2304)
	CPAN: YAML::XS loaded ok (v0.39)
	CPAN: Parse::CPAN::Meta loaded ok (v1.4414)
	CPAN: CPAN::Meta loaded ok (v2.141520)
	CPAN: Module::CoreList loaded ok (v5.021001)
	CPAN: Time::HiRes loaded ok (v1.9726)
	Configuring M/MS/MSCHWERN/URI-Find-20140709.tar.gz with Build.PL
	Created MYMETA.yml and MYMETA.json
	Creating new 'Build' script for 'URI-Find' version '20140709'
	  MSCHWERN/URI-Find-20140709.tar.gz
	  C:\strawberry\perl\bin\perl.exe Build.PL -- OK
	Running Build for M/MS/MSCHWERN/URI-Find-20140709.tar.gz
	Building URI-Find
	  MSCHWERN/URI-Find-20140709.tar.gz
	  C:\strawberry\perl\bin\perl.exe ./Build -- OK
	Running Build test
	t/Find.t ................ Useless use of private variable in void context at C:/strawberry/perl/lib/Test/More.pm line 68
	9.
	Useless use of private variable in void context at C:/strawberry/perl/lib/Test/More.pm line 689.
	Unquoted string "check" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1001.
	Unquoted string "regex" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1001.
	Bareword found where operator expected at C:/strawberry/perl/lib/Test/More.pm line 1001, near "times you"
			(Do you need to predeclare times?)
	Unquoted string "equivalent" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1002.
	Unquoted string "filehandles" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1005.
	Unquoted string "over" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1007.
	Number found where operator expected at C:/strawberry/perl/lib/Test/More.pm line 1007, near "over 4"
			(Do you need to predeclare over?)
	Bareword found where operator expected at C:/strawberry/perl/lib/Test/More.pm line 1011, near "is_deeply"
			(Missing semicolon on previous line?)
	Bareword found where operator expected at C:/strawberry/perl/lib/Test/More.pm line 1013, near "$expected are"
			(Missing operator before are?)
	Unquoted string "equivalent" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1015.
	Unquoted string "differing" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1016.
	Bareword found where operator expected at C:/strawberry/perl/lib/Test/More.pm line 1018, near ") compares"
			(Missing operator before compares?)
	Unquoted string "dereferenced" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1018.
	Unquoted string "except" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1019.
	Bareword found where operator expected at C:/strawberry/perl/lib/Test/More.pm line 1019, near ") are"
			(Missing operator before are?)
	Unquoted string "considered" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1020.
	String found where operator expected at C:/strawberry/perl/lib/Test/More.pm line 1020, near "considered "different""
			(Do you need to predeclare considered?)
	Bareword found where operator expected at C:/strawberry/perl/lib/Test/More.pm line 1022, near ") currently"
			(Missing operator before currently?)
	Unquoted string "globs" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1023.
	Unquoted string "checks" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1023.
	Unquoted string "referent" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1023.
	Unquoted string "in" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1026.
	Unquoted string "lines" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1027.
	Unquoted string "cut" may clash with future reserved word at C:/strawberry/perl/lib/Test/More.pm line 1031.
	Variable "$DNE" will not stay shared at C:/strawberry/perl/lib/Test/More.pm line 1035.
	Not enough arguments for Test::More::is at C:/strawberry/perl/lib/Test/More.pm line 1001, near "check or"
	syntax error at C:/strawberry/perl/lib/Test/More.pm line 1002, near "times you
	need "
	Not enough arguments for Test::More::is at C:/strawberry/perl/lib/Test/More.pm line 1013, near "()"
	syntax error at C:/strawberry/perl/lib/Test/More.pm line 1013, near "$expected are references"
	BEGIN not safe after errors--compilation aborted at C:/strawberry/perl/lib/Test/More.pm line 1305.
	Compilation failed in require at t/Find.t line 6.
	BEGIN failed--compilation aborted at t/Find.t line 6.
	t/Find.t ................ Dubious, test returned 255 (wstat 65280, 0xff00)
	No subtests run
	t/filter.t .............. ok
	t/html.t ................ ok
	t/is_schemed.t .......... ok
	t/load-schemeless.t ..... ok
	t/rfc3986_appendix_c.t .. ok
	t/urifind/find.t ........ ok
	t/urifind/pod.t ......... ok

	Test Summary Report
	-------------------
	t/Find.t              (Wstat: 65280 Tests: 0 Failed: 0)
	  Non-zero exit status: 255
	  Parse errors: No plan found in TAP output
	Files=8, Tests=41,  4 wallclock secs ( 0.17 usr +  0.08 sys =  0.25 CPU)
	Result: FAIL
	Failed 1/8 test programs. 0/41 subtests failed.
	  MSCHWERN/URI-Find-20140709.tar.gz
	  C:\strawberry\perl\bin\perl.exe ./Build test -- NOT OK
	//hint// to see the cpan-testers results for installing this module, try:
	  reports MSCHWERN/URI-Find-20140709.tar.gz
	  

//EDIT:  
**Install with cpan works with perl 5.14.4.1 and Test::More 0.98**

cpan install ok with Strawberry Perl versions:
5.10
5.12
5.16
5.18
5.20

The problematic code is in Find.t (https://github.com/schwern/URI-Find/blob/master/t/Find.t#L5)

      use open ':std', ':encoding(utf8)'; 

If i comment the line, the test with Build test runs, but show warnings about:

    t/Find.t ................ 1/? Wide character in print at C:/strawberry/perl/lib/Test/Builder.pm line 1821.
    Wide character in print at C:/strawberry/perl/lib/Test/Builder.pm line 1821.
    Wide character in print at C:/strawberry/perl/lib/Test/Builder.pm line 1821.
    Wide character in print at C:/strawberry/perl/lib/Test/Builder.pm line 1821.
    Wide character in print at C:/strawberry/perl/lib/Test/Builder.pm line 1821.

**Comment by schwern** [comment]
Looks like it was a Test::More issue.
